### ISSUE TITLE
Add competitor to key statistic page for each company

### ISSUE THREAD

**Issue by shibbyshibby** [Shibbywan/FinancialFlo#10]
Add competitor as shown in this format
![](http://i.imgur.com/ToivPAe.jpg)

**Comment by Shibbywan** [comment]
Completed:

![](http://i.imgur.com/dMW5I6J.png)

**Comment by Shibbywan** [comment]
@shibbyshibby honestly it should be you closing the issues to confirm that what you wanted has been completed.
